# Generated by Django 5.0.6 on 2024-05-28 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('user_name', models.CharField(default='', max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Domiciliario',
            fields=[
                ('codigo_domiciliario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('medio_transporte', models.CharField(max_length=50)),
                ('licencia_conduccion', models.CharField(max_length=50)),
                ('fecha_vencimiento_licencia', models.DateField()),
                ('horario_disponibilidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=100)),
                ('imagen', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codigo_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(auto_now=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('tipo_entrega', models.CharField(max_length=50)),
                ('codigo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('codigo_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField()),
                ('hora_envio', models.TimeField()),
                ('fecha_fin', models.DateField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(default='En camino', max_length=50)),
                ('codigo_domiciliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.domiciliario')),
                ('codigo_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('codigo_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedido')),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('codigo_venta', models.AutoField(primary_key=True, serialize=False)),
                ('hora_venta', models.TimeField(auto_now=True)),
                ('fecha_venta', models.DateField(auto_now=True)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('productos', models.ManyToManyField(through='ventas.DetalleVenta', to='ventas.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_venta',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
        ),
    ]
