# Generated by Django 5.0.6 on 2024-05-31 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='fecha_fin',
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_domiciliario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.domiciliario'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='codigo_domiciliario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.domiciliario'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='fecha_envio',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='hora_envio',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ColaDomiciliarios',
            fields=[
                ('codigo_cola', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('codigo_domiciliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.domiciliario')),
            ],
        ),
    ]
