# Generated by Django 5.0.6 on 2024-06-05 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetallePedido',
        ),
    ]
