# Generated by Django 5.0.6 on 2024-05-27 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cliente_password_cliente_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventas.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
