# Generated by Django 5.0.6 on 2024-06-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_delete_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
