# Generated by Django 5.0.6 on 2024-05-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_pedido_codigo_producto_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.URLField(default=''),
        ),
    ]
